export default
[
    {
       "sym":"EURUSD",
       "img":"meta-fx.trade/icons/EURUSD.png"
    },
    {
       "sym":"GBPUSD",
       "img":"meta-fx.trade/icons/GBPUSD.png"
    },
    {
       "sym":"USDCHF",
       "img":"meta-fx.trade/icons/USDCHF.png"
    },
    {
       "sym":"USDJPY",
       "img":"meta-fx.trade/icons/USDJPY.png"
    },
    {
       "sym":"USDCNH",
       "img":"meta-fx.trade/icons/USDCNH.png"
    },
    {
       "sym":"USDRUB",
       "img":"meta-fx.trade/icons/USDRUB.png"
    },
    {
       "sym":"AUDUSD",
       "img":"meta-fx.trade/icons/AUDUSD.png"
    },
    {
       "sym":"NZDUSD",
       "img":"meta-fx.trade/icons/NZDUSD.png"
    },
    {
       "sym":"USDCAD",
       "img":"meta-fx.trade/icons/USDCAD.png"
    },
    {
       "sym":"USDSEK",
       "img":"meta-fx.trade/icons/USDSEK.png"
    },
    {
       "sym":"USDHKD",
       "img":"meta-fx.trade/icons/USDHKD.png"
    },
    {
       "sym":"USDSGD",
       "img":"meta-fx.trade/icons/USDSGD.png"
    },
    {
       "sym":"USDNOK",
       "img":"meta-fx.trade/icons/USDNOK.png"
    },
    {
       "sym":"USDDKK",
       "img":"meta-fx.trade/icons/USDDKK.png"
    },
    {
       "sym":"USDTRY",
       "img":"meta-fx.trade/icons/USDTRY.png"
    },
    {
       "sym":"USDZAR",
       "img":"meta-fx.trade/icons/USDZAR.png"
    },
    {
       "sym":"USDCZK",
       "img":"meta-fx.trade/icons/USDCZK.png"
    },
    {
       "sym":"USDHUF",
       "img":"meta-fx.trade/icons/USDHUF.png"
    },
    {
       "sym":"USDPLN",
       "img":"meta-fx.trade/icons/USDPLN.png"
    },
    {
       "sym":"USDRUR",
       "img":"meta-fx.trade/icons/USDRUR.png"
    },
    {
       "sym":"AUDCAD",
       "img":"meta-fx.trade/icons/AUDCAD.png"
    },
    {
       "sym":"AUDCHF",
       "img":"meta-fx.trade/icons/AUDCHF.png"
    },
    {
       "sym":"AUDJPY",
       "img":"meta-fx.trade/icons/AUDJPY.png"
    },
    {
       "sym":"AUDNZD",
       "img":"meta-fx.trade/icons/AUDNZD.png"
    },
    {
       "sym":"CADCHF",
       "img":"meta-fx.trade/icons/CADCHF.png"
    },
    {
       "sym":"CADJPY",
       "img":"meta-fx.trade/icons/CADJPY.png"
    },
    {
       "sym":"CHFJPY",
       "img":"meta-fx.trade/icons/CHFJPY.png"
    },
    {
       "sym":"EURAUD",
       "img":"meta-fx.trade/icons/EURAUD.png"
    },
    {
       "sym":"EURCAD",
       "img":"meta-fx.trade/icons/EURCAD.png"
    },
    {
       "sym":"EURCHF",
       "img":"meta-fx.trade/icons/EURCHF.png"
    },
    {
       "sym":"EURCZK",
       "img":"meta-fx.trade/icons/EURCZK.png"
    },
    {
       "sym":"EURDKK",
       "img":"meta-fx.trade/icons/EURDKK.png"
    },
    {
       "sym":"EURGBP",
       "img":"meta-fx.trade/icons/EURGBP.png"
    },
    {
       "sym":"EURHKD",
       "img":"meta-fx.trade/icons/EURHKD.png"
    },
    {
       "sym":"EURHUF",
       "img":"meta-fx.trade/icons/EURHUF.png"
    },
    {
       "sym":"EURJPY",
       "img":"meta-fx.trade/icons/EURJPY.png"
    },
    {
       "sym":"EURNOK",
       "img":"meta-fx.trade/icons/EURNOK.png"
    },
    {
       "sym":"EURNZD",
       "img":"meta-fx.trade/icons/EURNZD.png"
    },
    {
       "sym":"EURPLN",
       "img":"meta-fx.trade/icons/EURPLN.png"
    },
    {
       "sym":"EURRUR",
       "img":"meta-fx.trade/icons/EURRUR.png"
    },
    {
       "sym":"EURRUB",
       "img":"meta-fx.trade/icons/EURRUB.png"
    },
    {
       "sym":"EURSEK",
       "img":"meta-fx.trade/icons/EURSEK.png"
    },
    {
       "sym":"EURTRY",
       "img":"meta-fx.trade/icons/EURTRY.png"
    },
    {
       "sym":"EURZAR",
       "img":"meta-fx.trade/icons/EURZAR.png"
    },
    {
       "sym":"GBPAUD",
       "img":"meta-fx.trade/icons/GBPAUD.png"
    },
    {
       "sym":"GBPCHF",
       "img":"meta-fx.trade/icons/GBPCHF.png"
    },
    {
       "sym":"GBPJPY",
       "img":"meta-fx.trade/icons/GBPJPY.png"
    },
    {
       "sym":"XAUUSD",
       "img":"meta-fx.trade/icons/XAUUSD.png"
    },
    {
       "sym":"XAUEUR",
       "img":"meta-fx.trade/icons/XAUEUR.png"
    },
    {
       "sym":"XAUAUD",
       "img":"meta-fx.trade/icons/XAUAUD.png"
    },
    {
       "sym":"XAGUSD",
       "img":"meta-fx.trade/icons/XAGUSD.png"
    },
    {
       "sym":"XAGEUR",
       "img":"meta-fx.trade/icons/XAGEUR.png"
    },
    {
       "sym":"GBPCAD",
       "img":"meta-fx.trade/icons/GBPCAD.png"
    },
    {
       "sym":"GBPNOK",
       "img":"meta-fx.trade/icons/GBPNOK.png"
    },
    {
       "sym":"GBPNZD",
       "img":"meta-fx.trade/icons/GBPNZD.png"
    },
    {
       "sym":"GBPPLN",
       "img":"meta-fx.trade/icons/GBPPLN.png"
    },
    {
       "sym":"GBPSEK",
       "img":"meta-fx.trade/icons/GBPSEK.png"
    },
    {
       "sym":"GBPSGD",
       "img":"meta-fx.trade/icons/GBPSGD.png"
    },
    {
       "sym":"GBPZAR",
       "img":"meta-fx.trade/icons/GBPZAR.png"
    },
    {
       "sym":"NZDCAD",
       "img":"meta-fx.trade/icons/NZDCAD.png"
    },
    {
       "sym":"NZDCHF",
       "img":"meta-fx.trade/icons/NZDCHF.png"
    },
    {
       "sym":"NZDJPY",
       "img":"meta-fx.trade/icons/NZDJPY.png"
    },
    {
       "sym":"NZDSGD",
       "img":"meta-fx.trade/icons/NZDSGD.png"
    },
    {
       "sym":"SGDJPY",
       "img":"meta-fx.trade/icons/SGDJPY.png"
    },
    {
       "sym":"XPDUSD",
       "img":"meta-fx.trade/icons/XPDUSD.png"
    },
    {
       "sym":"XPTUSD",
       "img":"meta-fx.trade/icons/XPTUSD.png"
    },
    {
       "sym":"USDGEL",
       "img":"meta-fx.trade/icons/USDGEL.png"
    },
    {
       "sym":"USDMXN",
       "img":"meta-fx.trade/icons/USDMXN.png"
    },
    {
       "sym":"EURMXN",
       "img":"meta-fx.trade/icons/EURMXN.png"
    },
    {
       "sym":"GBPMXN",
       "img":"meta-fx.trade/icons/GBPMXN.png"
    },
    {
       "sym":"CADMXN",
       "img":"meta-fx.trade/icons/CADMXN.png"
    },
    {
       "sym":"CHFMXN",
       "img":"meta-fx.trade/icons/CHFMXN.png"
    },
    {
       "sym":"MXNJPY",
       "img":"meta-fx.trade/icons/MXNJPY.png"
    },
    {
       "sym":"NZDMXN",
       "img":"meta-fx.trade/icons/NZDMXN.png"
    },
    {
       "sym":"USDCOP",
       "img":"meta-fx.trade/icons/USDCOP.png"
    },
    {
       "sym":"USDARS",
       "img":"meta-fx.trade/icons/USDARS.png"
    },
    {
       "sym":"USDCLP",
       "img":"meta-fx.trade/icons/USDCLP.png"
    }
 ]